module.exports = function getMethods() {
	// methods that require extra parameters are disabled for now
	return [
		'camelize',
		'capitalize',
		'chars',
		// 'chop',
		'classify',
		'clean',
		'cleanDiacritics',
		// 'count',
		'dasherize',
		'decapitalize',
		// 'dedent',
		// 'endsWith',
		'escapeHTML',
		'escapeRegExp',
		'humanize',
		// 'include',
		// 'insert',
		// 'isBlank',
		// 'join',
		// 'levenshtein',
		'lines',
		// 'lpad',
		// 'lrpad',
		'ltrim',
		// 'map',
		// 'naturalCmp',
		// 'numberFormat',
		// 'pad',
		'pred',
		// 'prune',
		'quote',
		// 'repeat',
		// 'replaceAll',
		'reverse',
		// 'rpad',
		'rtrim',
		'slugify',
		// 'splice',
		// 'startsWith',
		// 'strLeft',
		// 'strLeftBack',
		// 'strRight',
		// 'strRightBack',
		'stripTags',
		'succ',
		// 'surround',
		'swapCase',
		'titleize',
		'toNumber',
		// 'toSentence',
		// 'toSentenceSerial',
		'trim',
		// 'truncate',
		'underscored',
		'unescapeHTML',
		'unquote',
		'words',
		// 'wrap',
	];
};
